"""empty message

Revision ID: 758fa8a68445
Revises: 9c216a077790
Create Date: 2023-03-31 16:49:43.745864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '758fa8a68445'
down_revision = '9c216a077790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', mysql.VARCHAR(length=30), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
